// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gym.Models;

public partial class IdentityTable
{
    public int Id { get; set; }

    public string IdentityTitle { get; set; }

    public virtual ICollection<MemberSummaryTable> MemberSummaryTable { get; set; } = new List<MemberSummaryTable>();
}