// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gym.Models;

public partial class MemberSummaryTable
{
    public string Name { get; set; }

    public string Phone { get; set; }

    public int? Gender { get; set; }

    public DateTime? Birthday { get; set; }

    public string FamilyName { get; set; }

    public string FamilyPhone { get; set; }

    public string Line { get; set; }

    public int Id { get; set; }

    public string Email { get; set; }

    public int? StatusId { get; set; }

    public int? IdentityLevelId { get; set; }

    public int? RemainingCourse { get; set; }

    public string PassWord { get; set; }

    public virtual ICollection<CourseTotalTable> CourseTotalTable { get; set; } = new List<CourseTotalTable>();

    public virtual GenderTable GenderNavigation { get; set; }

    public virtual IdentityTable IdentityLevel { get; set; }

    public virtual ICollection<MemberMessageTable> MemberMessageTable { get; set; } = new List<MemberMessageTable>();

    public virtual ICollection<OrderTable> OrderTable { get; set; } = new List<OrderTable>();

    public virtual StatusTable Status { get; set; }

    public virtual ICollection<StudentCourseTable> StudentCourseTable { get; set; } = new List<StudentCourseTable>();
}