// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gym.Models;

public partial class OrderTable
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public int? ProductId { get; set; }

    public int? StatusId { get; set; }

    public int? UnPaidInstallment { get; set; }

    public int? PaidInstallment { get; set; }

    public int? OrderPrice { get; set; }

    public int? UnPaidPrice { get; set; }

    public int? PaidPrice { get; set; }

    public int? Back5Number { get; set; }

    public bool? Approval { get; set; }

    public DateTime? OrderDate { get; set; }

    public int? CourseCounts { get; set; }

    public virtual MemberSummaryTable Member { get; set; }

    public virtual ICollection<OrderDetialTable> OrderDetialTable { get; set; } = new List<OrderDetialTable>();

    public virtual ProductsTable Product { get; set; }

    public virtual StatusTable Status { get; set; }

    public virtual ICollection<StudentCourseTable> StudentCourseTable { get; set; } = new List<StudentCourseTable>();
}