// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gym.Models;

public partial class ProductsTable
{
    public int Id { get; set; }

    public string ProductName { get; set; }

    public int? ProductCapacity { get; set; }

    public int? Price { get; set; }

    public int? DueDay { get; set; }

    public virtual ICollection<OrderDetialTable> OrderDetialTable { get; set; } = new List<OrderDetialTable>();

    public virtual ICollection<OrderTable> OrderTable { get; set; } = new List<OrderTable>();

    public virtual ICollection<StudentCourseTable> StudentCourseTable { get; set; } = new List<StudentCourseTable>();
}