// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gym.Models;

public partial class StatusTable
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int? TypeId { get; set; }

    public virtual ICollection<CourseTotalTable> CourseTotalTable { get; set; } = new List<CourseTotalTable>();

    public virtual ICollection<MemberSummaryTable> MemberSummaryTable { get; set; } = new List<MemberSummaryTable>();

    public virtual ICollection<OrderTable> OrderTable { get; set; } = new List<OrderTable>();

    public virtual ICollection<StudentCourseTable> StudentCourseTable { get; set; } = new List<StudentCourseTable>();

    public virtual TypeTable Type { get; set; }
}