// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gym.Models;

public partial class TypeTable
{
    public int Id { get; set; }

    public string TypeDepiction { get; set; }

    public virtual ICollection<StatusTable> StatusTable { get; set; } = new List<StatusTable>();
}